### ISSUE TITLE
Fatal error suddenly in all requests

### ISSUE THREAD

**Issue by samyb8** [Lusitanian/PHPoAuthLib#208]
Performing simple requests that used to work:
$result2 = json_decode($etsyService->request('/receipts/'.$receiptNumber));

And suddenly all my requests are returning this error:

Fatal error: Uncaught exception 'OAuth\Common\Http\Exception\TokenResponseException' with message 'file_get_contents(https://openapi.etsy.com/v2/receipts/126422362): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden ' in /hermes/bosoraweb013/b1151/ipg.tahara/APIs/PHPoAuthLib-master/src/OAuth/Common/Http/Client/StreamClient.php:70 Stack trace: #0 /hermes/bosoraweb013/b1151/ipg.tahara/APIs/PHPoAuthLib-master/src/OAuth/OAuth1/Service/AbstractService.php(137): OAuth\Common\Http\Client\StreamClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), NULL, Array, 'GET') #1 /hermes/bosoraweb013/b1151/ipg.tahara/APIs/PHPoAuthLib-master/examples/CheckOpen.php(65): OAuth\OAuth1\Service\AbstractService->request('/receipts/12642...') #2 {main} thrown in /hermes/bosoraweb013/b1151/ipg.tahara/APIs/PHPoAuthLib-master/src/OAuth/Common/Http/Client/StreamClient.php on line 70

**Comment by tezrik** [comment]
This issue has been marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.
