### ISSUE TITLE
Registering custom service class doesn't work

### ISSUE THREAD

**Issue by samwilson** [Lusitanian/PHPoAuthLib#499]
I'm getting an error when I try to register a custom service class for the Flickr service.

Even with a completely empty subclass of flickr:

```php
<?php
namespace Samwilson\FlickrTest;
class FlickrService extends \OAuth\OAuth1\Service\Flickr {
}
```
The following
```php
$serviceFactory->registerService( 'Flickr', \Samwilson\FlickrTest\FlickrService::class );
```

(It doesn't make any difference if I give it a new service name either.)

The error is:

```
PHP Fatal error:  Uncaught OAuth\Common\Storage\Exception\TokenNotFoundException:
Token not stored in /home/flickr-test/vendor/lusitanian/oauth/src/OAuth/Common/Storage/Memory.php:39
Stack trace:
#0 /home/sam/flickr-test/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/Flickr.php(91): OAuth\Common\Storage\Memory->retrieveAccessToken('FlickrService')
#1 /home/sam/flickr-test/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/Flickr.php(124): OAuth\OAuth1\Service\Flickr->request('flickr.test.log...', 'POST', Array, Array)
#2 /home/sam/flickr-test/src/UpDown.php(77): OAuth\OAuth1\Service\Flickr->requestJson('flickr.test.log...', 'POST', Array)
```

**Comment by samwilson** [comment]
Oh! I see. The new service class is reporting its name as being the same as its class, but in my case that isn't true.

I just needed to override `Flickr::service()`:

```php
<?php
namespace Samwilson\FlickrTest;
class FlickrService extends \OAuth\OAuth1\Service\Flickr {
    public function service() {
        return 'Flickr';
    }
}
```

And all is okay.

Thanks! (I'll just leave this here for anyone else to find if they get confused like me. :-))
