### ISSUE TITLE
How do I provide my own Access Token?

### ISSUE THREAD

**Issue by whiterook6** [Lusitanian/PHPoAuthLib#513]
We're using an in-app browser plugin for cordova that opens a login form for facebook and, if successful, returns an access token. All of the examples show how to login with a code, but get the tokens themselves. How can I we provide our own access token and complete the flow?

I tried this:
```
$service = OAuth::consumer('Facebook);
$token = new StdOAuth2Token();
$token->setAccessToken('A totally valid access token here');

$service->getStorage()->storeAccessToken($service, $token);
$result = json_decode($service->request('/me?fields=id,email,first_name,last_name'),
	true,
	512,
	JSON_BIGINT_AS_STRING);
```

but we get an HTTP401 - Unauthorized error when calling `$service->request()`:

```
OAuth\Common\Http\Exception\TokenResponseException: Failed to request resource. HTTP Code: HTTP/1.1 401 Unauthorized in /var/www/johnny_dev/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php:68
Stack trace:
#0 /var/www/johnny_dev/vendor/lusitanian/oauth/src/OAuth/OAuth2/Service/AbstractService.php(183): OAuth\Common\Http\Client\StreamClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), NULL, Array, 'GET')
#1 /var/www/johnny_dev/modules/Authentication/src/AuthenticationController.php(103): OAuth\OAuth2\Service\AbstractService->request('/me?fields=id,e...')
...
```

**Comment by txwizard** [comment]
You cannot, because that breaks the protocol by defeating the purpose of requesting the access token from the IdP. The access token is your API key, a security credential, and it must be issued by the identity provider, just as the badge that lets you into a secure building must be issued by its occupant's security office.
